mink: 2
maxk: 10
k: 0
data: norm26531ON.csv
markers:
- S100
- KI67
- CD4
- CD45RO
- ECAD
- cJUN
- MITF
- pS6
- VEGFR2
- VIMENTIN
- CD3
- FOXP3
- pRB
- KERATIN
- CD45
- SMA
- PDL1
- CD8
- PD1
- CATENIN
- NGFR
- HES1
- pERKz
samplesize: 10000
