mink: 2
<<<<<<< HEAD
maxk: 3
k: 0
data: norm25546POST.csv
=======
maxk: 10
k: 0
data: norm26531ON.csv
>>>>>>> 1766239020b50d79882ffea7abb3216ec407cdf0
markers:
- S100
- KI67
- CD4
- CD45RO
- ECAD
- cJUN
- MITF
- pS6
- VEGFR2
- VIMENTIN
- CD3
- FOXP3
- pRB
- KERATIN
- CD45
- SMA
- PDL1
- CD8
- PD1
- CATENIN
- NGFR
- HES1
- pERKz
<<<<<<< HEAD
sampleratio: 0.005
=======
samplesize: 10000
>>>>>>> 1766239020b50d79882ffea7abb3216ec407cdf0
